// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/2/2026, 8:56:59 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/workspace/byoip-ui/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspace/byoip-ui/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspace/byoip-ui/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspace/byoip-ui/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspace/byoip-ui/plugins/**/*.{js,ts,mjs}","/workspace/byoip-ui/composables/**/*.{js,ts,mjs}","/workspace/byoip-ui/utils/**/*.{js,ts,mjs}","/workspace/byoip-ui/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspace/byoip-ui/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/workspace/byoip-ui/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/workspace/byoip-ui/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;